# Installation
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

# Plugin manager
- name: Makes sure autoload directory exists
  file: path="{{localsetup_user_home}}/.vim/autoload" state=directory

- name: Check if vim-plug is installed
  stat:
    path: "{{localsetup_user_home}}/.vim/autoload/plug.vim"
  register: vim_plug_check

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{localsetup_user_home}}/.vim/autoload/plug.vim"
  when: not vim_plug_check.stat.exists

# Snippets
- name: Makes sure UltiSnips directory exists
  file: path="{{localsetup_user_home}}/.vim/UltiSnips" state=directory

- name: Symlink all snippet files
  file:
    src: "{{ localsetup_home }}/roles/vim/files/{{item}}"
    dest: "{{ localsetup_user_home}}/.vim/UltiSnips/{{item}}"
    state: link
  with_items:
    - "python.snippets"
    - "rst.snippets"
    - "javascript.snippets"

# Configuration
- name: Check if vimrc exists
  stat: path="{{localsetup_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{localsetup_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ localsetup_home }}/roles/vim/files/vimrc"
    dest: "{{localsetup_user_home}}/.vimrc"
    state: link

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins|bool
